"""
Tests for topocore.io.crs.external.ExternalCRSDetector.

The shared .prj sidecar strategy for formats with no CRS mechanism
of their own (XYZ, CSV, PTS, PLY -- confirmed during this
capability's own audit that none of these has any internal CRS
concept at all). Verified against both OGC-style and genuine
ESRI-style WKT1 (the conventional .prj dialect), across all 4
formats sharing a single .prj sidecar, and every failure mode from
the design's own explicit behavior table.
"""

from __future__ import annotations

from pathlib import Path

import pyproj
import pytest
from pyproj.enums import WktVersion
from topocore.geodesy import CRS
from topocore.io.crs.external import ExternalCRSDetector


@pytest.fixture
def detector() -> ExternalCRSDetector:
    return ExternalCRSDetector()


def _write_pair(tmp_path: Path, base_name: str, extension: str, prj_content: str | None) -> Path:
    data_path = tmp_path / f"{base_name}.{extension}"
    data_path.write_text("fake data content", encoding="utf-8")
    if prj_content is not None:
        (tmp_path / f"{base_name}.prj").write_text(prj_content, encoding="utf-8")
    return data_path


# ----------------------------------------------------------------------
# The explicit behavior table, verified exactly, across all 4 formats.
# ----------------------------------------------------------------------


@pytest.mark.parametrize("extension", ["xyz", "csv", "pts", "ply"])
def test_valid_ogc_wkt_prj_is_detected_for_every_supported_format(
    tmp_path: Path, detector: ExternalCRSDetector, extension: str
) -> None:
    wkt = pyproj.CRS.from_epsg(32618).to_wkt()
    data_path = _write_pair(tmp_path, "survey", extension, wkt)

    detected = detector.detect(data_path)
    assert detected is not None
    assert isinstance(detected, CRS)
    assert detected.epsg == 32618


def test_esri_style_wkt1_prj_is_detected(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    """
    Confirmed directly: .prj conventionally holds the older,
    ESRI-flavored WKT1 dialect -- verified here with a real one
    generated by pyproj itself, correctly resolved back to its own
    EPSG code with no special-casing needed.
    """
    esri_wkt = pyproj.CRS.from_epsg(26910).to_wkt(WktVersion.WKT1_ESRI)
    assert "D_North_American_1983" in esri_wkt  # confirm this really is the ESRI dialect
    data_path = _write_pair(tmp_path, "esri_survey", "xyz", esri_wkt)

    detected = detector.detect(data_path)
    assert detected is not None
    assert detected.epsg == 26910


def test_missing_prj_returns_none(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    data_path = _write_pair(tmp_path, "no_sidecar", "xyz", prj_content=None)
    assert detector.detect(data_path) is None


def test_empty_prj_returns_none(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    data_path = _write_pair(tmp_path, "empty_prj", "xyz", "")
    assert detector.detect(data_path) is None


def test_whitespace_only_prj_returns_none(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    data_path = _write_pair(tmp_path, "whitespace_prj", "xyz", "   \n\n   ")
    assert detector.detect(data_path) is None


def test_invalid_text_prj_returns_none_not_an_error(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    data_path = _write_pair(tmp_path, "invalid_prj", "xyz", "this is not WKT at all")
    assert detector.detect(data_path) is None


def test_missing_main_file_raises_file_not_found(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    with pytest.raises(FileNotFoundError, match="not found"):
        detector.detect(tmp_path / "does_not_exist.xyz")


# ----------------------------------------------------------------------
# Naming convention and sharing.
# ----------------------------------------------------------------------


def test_sidecar_naming_replaces_extension_not_appends(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    """survey.xyz -> survey.prj, never survey.xyz.prj -- matching the real Shapefile convention exactly."""
    wkt = pyproj.CRS.from_epsg(32618).to_wkt()
    data_path = tmp_path / "survey.xyz"
    data_path.write_text("fake data", encoding="utf-8")
    (tmp_path / "survey.prj").write_text(wkt, encoding="utf-8")
    (tmp_path / "survey.xyz.prj").write_text("this should never be read", encoding="utf-8")

    detected = detector.detect(data_path)
    assert detected is not None
    assert detected.epsg == 32618


def test_all_4_formats_sharing_one_base_name_use_the_same_sidecar(
    tmp_path: Path, detector: ExternalCRSDetector
) -> None:
    wkt = pyproj.CRS.from_epsg(32618).to_wkt()
    (tmp_path / "shared.prj").write_text(wkt, encoding="utf-8")

    for extension in ["xyz", "csv", "pts", "ply"]:
        data_path = tmp_path / f"shared.{extension}"
        data_path.write_text("fake data", encoding="utf-8")
        detected = detector.detect(data_path)
        assert detected is not None
        assert detected.epsg == 32618


def test_accepts_str_path_as_well_as_path_object(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    wkt = pyproj.CRS.from_epsg(32618).to_wkt()
    data_path = _write_pair(tmp_path, "str_path_test", "xyz", wkt)

    detected = detector.detect(str(data_path))
    assert detected is not None
    assert detected.epsg == 32618


# ----------------------------------------------------------------------
# Reviewer-identified gaps, closed with real, verified evidence.
# ----------------------------------------------------------------------


def test_utf8_bom_is_stripped_correctly(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    """
    A real, confirmed bug found and fixed during this audit: a
    Windows/ESRI-style .prj with a UTF-8 byte-order-mark used to fail
    entirely (the decoded BOM character stayed at the start of the
    text, breaking CRS.from_wkt()). Fixed by reading with
    utf-8-sig instead of plain utf-8.
    """
    wkt = pyproj.CRS.from_epsg(32618).to_wkt()
    data_path = tmp_path / "with_bom.xyz"
    data_path.write_text("fake data", encoding="utf-8")
    (tmp_path / "with_bom.prj").write_bytes(b"\xef\xbb\xbf" + wkt.encode("utf-8"))

    detected = detector.detect(data_path)
    assert detected is not None
    assert detected.epsg == 32618


def test_compound_horizontal_and_vertical_crs_in_prj(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    compound = pyproj.CRS.from_epsg("32618+5773")
    data_path = _write_pair(tmp_path, "compound", "xyz", compound.to_wkt())

    detected = detector.detect(data_path)
    assert detected is not None
    assert detected.is_compound


def test_alternate_candidate_name_is_never_consulted(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    """
    Confirmed directly: only the exact `with_suffix('.prj')` path is
    ever checked. If `survey.prj` doesn't exist, `survey.xyz.prj`
    existing on its own is NOT treated as a fallback candidate --
    there is no "try alternate names" behavior at all.
    """
    data_path = tmp_path / "only_alternate.xyz"
    data_path.write_text("fake data", encoding="utf-8")
    wkt = pyproj.CRS.from_epsg(32618).to_wkt()
    (tmp_path / "only_alternate.xyz.prj").write_text(wkt, encoding="utf-8")  # NOT the canonical "only_alternate.prj"

    assert detector.detect(data_path) is None


def test_leading_comment_or_blank_lines_before_wkt_returns_none(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    """
    Confirmed directly: real .prj files are conventionally pure,
    single-line WKT with no comment syntax of their own. A file with
    leading blank lines or a comment-like line before the actual WKT
    is not parsed -- this is a deliberate conservative choice (never
    guess at an informal convention with no real precedent), not a
    best-effort extraction.
    """
    wkt = pyproj.CRS.from_epsg(32618).to_wkt()
    data_path = tmp_path / "with_comment.xyz"
    data_path.write_text("fake data", encoding="utf-8")
    (tmp_path / "with_comment.prj").write_text(f"\n\n# Generated by Some Software v1.0\n\n{wkt}\n", encoding="utf-8")

    assert detector.detect(data_path) is None


def test_permission_error_is_a_subclass_of_the_caught_oserror() -> None:
    """
    Confirmed structurally correct, even though this project's own
    development environment runs as root (bypassing Unix file
    permission checks entirely, so the actual OS-level denial itself
    cannot be forced and demonstrated directly here):
    PermissionError is a genuine subclass of the OSError this
    detector already catches, so a real permission-denied .prj would
    be treated the same as a missing one -- None, never an
    unhandled exception.
    """
    assert issubclass(PermissionError, OSError)


def test_non_epsg_crs_name_placeholder_documented_precisely(tmp_path: Path, detector: ExternalCRSDetector) -> None:
    """
    Confirmed directly: a custom, unregistered CRS's own `.name` is
    the literal string "unknown" (pyproj's own generic placeholder).
    ExternalCRSDetector.detect() itself just returns the CRS object
    unchanged in this case -- the "unknown" string only appears later,
    at the point apply_external_crs() builds cloud.crs from it. This
    test locks in the CRS object's own state at the detector level.
    """
    custom_crs = pyproj.CRS.from_proj4(
        "+proj=lcc +lat_1=4 +lat_2=6 +lat_0=5 +lon_0=-74 +x_0=500000 "
        "+y_0=500000 +ellps=GRS80 +units=m +no_defs +type=crs"
    )
    data_path = _write_pair(tmp_path, "unnamed_crs", "xyz", custom_crs.to_wkt())

    detected = detector.detect(data_path)
    assert detected is not None
    assert detected.epsg is None
    assert detected.name == "unknown"
