"""
topocore.features.feature_codes
===============================

Feature code registry.

This module provides the central registry used to map survey field
codes to the geometry that TopoCore must generate.

The registry is extensible and can be populated from multiple
catalogs or user-defined definitions.

Author
------
Hernán Mina

License
-------
MIT
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from enum import Enum


class FeatureGeometryType(Enum):
    """
    Geometry produced by a field code.
    """

    #: An isolated point, not connected to others sharing the code.
    POINT = "point"

    #: A point rendered as a CAD block/symbol (e.g. a tree, a pole).
    SYMBOL = "symbol"

    #: Consecutive same-code points connected into a polyline.
    LINE = "line"

    #: Consecutive same-code points connected into a closed polyline.
    POLYGON = "polygon"


@dataclass(frozen=True, slots=True)
class FeatureCodeDefinition:
    """
    Definition of a survey field code.

    Parameters
    ----------
    code
        Base survey code.

    name
        Human-readable name.

    geometry_type
        Geometry generated by the code.

    layer
        Default CAD/GIS layer.

    closed
        Whether generated geometry should be closed.

    aliases
        Alternative names accepted for the same feature.
    """

    code: str
    name: str
    geometry_type: FeatureGeometryType
    layer: str
    closed: bool = False
    aliases: tuple[str, ...] = ()


class FeatureCodeRegistry:
    """
    Registry of feature codes.

    Codes are stored case-insensitively.

    A registry may be initialized empty, from a dictionary,
    or populated using one or more catalogs.
    """

    __slots__ = ("_definitions",)

    def __init__(
        self,
        definitions: Iterable[FeatureCodeDefinition] | None = None,
    ) -> None:

        self._definitions: dict[
            str,
            FeatureCodeDefinition,
        ] = {}

        if definitions is not None:
            self.register_many(
                definitions,
            )

    @classmethod
    def default(
        cls,
    ) -> FeatureCodeRegistry:
        """
        Return the default TopoCore registry.
        """

        from topocore.features.catalogs import (
            ALL_CODES,
        )

        registry = cls()

        registry.register_many(
            ALL_CODES,
        )

        return registry

    def register(
        self,
        definition: FeatureCodeDefinition,
    ) -> None:
        """
        Register one definition.
        """

        key = definition.code.upper()

        self._definitions[key] = definition

        for alias in definition.aliases:
            self._definitions[alias.upper()] = definition

    def register_many(
        self,
        definitions: Iterable[FeatureCodeDefinition,],
    ) -> None:
        """
        Register multiple definitions.

        Parameters
        ----------
        definitions
            Definitions to register.
        """
        for definition in definitions:
            self.register(definition)

    def extend(
        self,
        definitions: Iterable[FeatureCodeDefinition,],
    ) -> FeatureCodeRegistry:
        """
        Extend the registry.

        Parameters
        ----------
        definitions
            Definitions to register.

        Returns
        -------
        FeatureCodeRegistry
            Self, allowing fluent chaining.
        """
        self.register_many(definitions)

        return self

    def get(
        self,
        code: str,
    ) -> FeatureCodeDefinition | None:
        """
        Return a feature definition.

        Parameters
        ----------
        code
            Survey field code.

        Returns
        -------
        FeatureCodeDefinition | None
        """
        return self._definitions.get(
            code.upper(),
        )

    def require(
        self,
        code: str,
    ) -> FeatureCodeDefinition:
        """
        Return a definition or raise KeyError.

        Parameters
        ----------
        code
            Survey field code.

        Raises
        ------
        KeyError
            Unknown feature code.
        """
        definition = self.get(code)

        if definition is None:
            raise KeyError(code)

        return definition

    @property
    def definitions(
        self,
    ) -> tuple[
        FeatureCodeDefinition,
        ...,
    ]:
        """
        Registered definitions.

        Aliases are removed.
        """
        return tuple(
            dict.fromkeys(
                self._definitions.values(),
            )
        )

    @property
    def codes(
        self,
    ) -> tuple[str, ...]:
        """
        Primary registered codes.
        """
        return tuple(definition.code for definition in self.definitions)

    @property
    def layers(
        self,
    ) -> tuple[str, ...]:
        """
        Registered layers.
        """
        return tuple(sorted({definition.layer for definition in self.definitions}))

    @property
    def size(
        self,
    ) -> int:
        """
        Number of primary definitions.
        """
        return len(
            self.definitions,
        )

    def find_by_layer(
        self,
        layer: str,
    ) -> tuple[
        FeatureCodeDefinition,
        ...,
    ]:
        """
        Return definitions belonging to a layer.
        """
        return tuple(definition for definition in self.definitions if definition.layer.upper() == layer.upper())

    def find_by_geometry(
        self,
        geometry_type: FeatureGeometryType,
    ) -> tuple[
        FeatureCodeDefinition,
        ...,
    ]:
        """
        Return definitions producing a geometry type.
        """
        return tuple(definition for definition in self.definitions if definition.geometry_type is geometry_type)

    def clear(
        self,
    ) -> None:
        """
        Remove all definitions.
        """
        self._definitions.clear()

    def copy(
        self,
    ) -> FeatureCodeRegistry:
        """
        Return a copy of the registry.
        """
        return FeatureCodeRegistry(
            self.definitions,
        )

    def __contains__(
        self,
        code: str,
    ) -> bool:
        return code.upper() in self._definitions

    def __len__(
        self,
    ) -> int:
        return self.size

    def __iter__(
        self,
    ):
        return iter(
            self.definitions,
        )


__all__ = [
    "FeatureGeometryType",
    "FeatureCodeDefinition",
    "FeatureCodeRegistry",
]
