from __future__ import annotations

DEFAULT_DXF_VERSION = "R2010"
APPID = "TOPOCORE"
SCHEMA_VERSION = "1.0"
DEFAULT_INDEX_CONTOUR_EVERY = 5

__all__ = ["DEFAULT_DXF_VERSION", "APPID", "SCHEMA_VERSION", "DEFAULT_INDEX_CONTOUR_EVERY"]
