"""
Coverage audit tests for topocore.io.ply.header_parser.PLYHeaderParser.

PR22 coverage hardening. Zero dedicated tests existed for this module
in this audit's sandbox before this suite -- genuinely untested
infrastructure, exhaustively verified with real, hand-crafted PLY
headers via BufferedReader-wrapped BytesIO streams.

Two branches confirmed unreachable, both via direct execution before
concluding:
  - _validate_magic()'s own "Empty PLY file" check: unreachable from
    parse()'s own calling convention, since parse()'s own `while
    True: readline()` loop already raises "Unexpected end of file"
    the moment the FIRST readline() call returns b"" -- lines can
    never be empty by the time _build_header()/_validate_magic() are
    reached through parse(). Confirmed by calling the (single-
    underscore, but a plain callable) staticmethod directly with an
    empty list -- its own contract works correctly in isolation, it
    just never triggers through the public parse() entry point.
  - _build_header()'s "PLY header does not declare a version" check:
    confirmed unreachable given _handle_format() always sets
    state.fmt and state.version ATOMICALLY together (both only after
    both of format/version pass their own validation) -- there is no
    way for one to be set without the other, making the separate
    version-is-None check dead code once the format-is-None check
    has already passed.
"""

from __future__ import annotations

import io

import pytest
from topocore.io.ply.exceptions import InvalidPLYError
from topocore.io.ply.header import PLYHeader, PLYListProperty
from topocore.io.ply.header_parser import PLYHeaderParser


def _parse(text: str) -> PLYHeader:
    stream = io.BufferedReader(io.BytesIO(text.encode("utf-8")))
    return PLYHeaderParser.parse(stream)  # type: ignore[arg-type]


# ----------------------------------------------------------------------
# Happy path.
# ----------------------------------------------------------------------


def test_parse_full_valid_header() -> None:
    text = (
        "ply\n"
        "format ascii 1.0\n"
        "comment created by test\n"
        "element vertex 100\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "element face 50\n"
        "property list uchar int vertex_indices\n"
        "end_header\n"
    )
    header = _parse(text)

    assert header.format.value == "ascii"
    assert header.version == "1.0"
    assert header.comments == ["created by test"]
    assert [e.name for e in header.elements] == ["vertex", "face"]
    assert [p.name for p in header.elements[0].properties] == ["x", "y", "z"]

    face_props = header.elements[1].properties
    list_prop = face_props[0]
    assert isinstance(list_prop, PLYListProperty)
    assert list_prop.name == "vertex_indices"
    assert list_prop.count_type.value == "uchar"
    assert list_prop.value_type.value == "int"


def test_parse_captures_obj_info() -> None:
    text = "ply\nformat ascii 1.0\nobj_info generated by pytest\nelement vertex 1\nproperty float x\nend_header\n"
    header = _parse(text)
    assert header.obj_info == ["generated by pytest"]


# ----------------------------------------------------------------------
# Stream-level errors.
# ----------------------------------------------------------------------


def test_parse_rejects_eof_before_end_header() -> None:
    with pytest.raises(InvalidPLYError, match="Unexpected end of file"):
        _parse("ply\nformat ascii 1.0\n")


def test_parse_rejects_invalid_utf8() -> None:
    stream = io.BufferedReader(io.BytesIO(b"ply\n\xff\xfe invalid utf8\nend_header\n"))
    with pytest.raises(InvalidPLYError, match="not valid UTF-8"):
        PLYHeaderParser.parse(stream)  # type: ignore[arg-type]


def test_parse_rejects_invalid_signature() -> None:
    with pytest.raises(InvalidPLYError, match="Invalid PLY signature"):
        _parse("notply\nformat ascii 1.0\nend_header\n")


def test_validate_magic_rejects_empty_lines_directly() -> None:
    """Unreachable via parse() itself (EOF fires first) -- tested directly against its own standalone contract."""
    with pytest.raises(InvalidPLYError, match="Empty PLY file"):
        PLYHeaderParser._validate_magic([])


# ----------------------------------------------------------------------
# format declaration.
# ----------------------------------------------------------------------


def test_rejects_duplicate_format() -> None:
    with pytest.raises(InvalidPLYError, match="Duplicate format"):
        _parse("ply\nformat ascii 1.0\nformat ascii 1.0\nend_header\n")


def test_rejects_malformed_format() -> None:
    with pytest.raises(InvalidPLYError, match="Malformed format"):
        _parse("ply\nformat ascii\nend_header\n")


def test_rejects_unsupported_format_value() -> None:
    with pytest.raises(InvalidPLYError, match="Unsupported PLY format"):
        _parse("ply\nformat bogus 1.0\nend_header\n")


def test_rejects_unsupported_version() -> None:
    with pytest.raises(InvalidPLYError, match="Unsupported PLY version"):
        _parse("ply\nformat ascii 2.0\nend_header\n")


def test_rejects_missing_format_declaration() -> None:
    with pytest.raises(InvalidPLYError, match="does not declare a format"):
        _parse("ply\nelement vertex 1\nproperty float x\nend_header\n")


# ----------------------------------------------------------------------
# element declaration.
# ----------------------------------------------------------------------


def test_rejects_malformed_element() -> None:
    with pytest.raises(InvalidPLYError, match="Malformed element"):
        _parse("ply\nformat ascii 1.0\nelement vertex\nend_header\n")


def test_rejects_invalid_element_count() -> None:
    with pytest.raises(InvalidPLYError, match="Invalid element count"):
        _parse("ply\nformat ascii 1.0\nelement vertex abc\nend_header\n")


def test_rejects_negative_element_count() -> None:
    with pytest.raises(InvalidPLYError, match="cannot be negative"):
        _parse("ply\nformat ascii 1.0\nelement vertex -5\nend_header\n")


def test_rejects_duplicate_element_name() -> None:
    with pytest.raises(InvalidPLYError, match="Duplicated element"):
        _parse("ply\nformat ascii 1.0\nelement vertex 10\nelement vertex 20\nend_header\n")


def test_rejects_no_elements_at_all() -> None:
    with pytest.raises(InvalidPLYError, match="contains no elements"):
        _parse("ply\nformat ascii 1.0\nend_header\n")


# ----------------------------------------------------------------------
# property declaration.
# ----------------------------------------------------------------------


def test_rejects_property_before_element() -> None:
    with pytest.raises(InvalidPLYError, match="before an element"):
        _parse("ply\nformat ascii 1.0\nproperty float x\nend_header\n")


def test_rejects_duplicate_property_name() -> None:
    with pytest.raises(InvalidPLYError, match="Duplicated property"):
        _parse("ply\nformat ascii 1.0\nelement vertex 10\nproperty float x\nproperty float x\nend_header\n")


def test_rejects_malformed_property_too_few_tokens() -> None:
    with pytest.raises(InvalidPLYError, match="Malformed property"):
        _parse("ply\nformat ascii 1.0\nelement vertex 10\nproperty\nend_header\n")


def test_rejects_malformed_scalar_property() -> None:
    with pytest.raises(InvalidPLYError, match="Malformed scalar property"):
        _parse("ply\nformat ascii 1.0\nelement vertex 10\nproperty float\nend_header\n")


def test_rejects_unsupported_scalar_type() -> None:
    with pytest.raises(InvalidPLYError, match="Unsupported scalar type"):
        _parse("ply\nformat ascii 1.0\nelement vertex 10\nproperty bogus x\nend_header\n")


def test_rejects_malformed_list_property() -> None:
    with pytest.raises(InvalidPLYError, match="Malformed list property"):
        _parse("ply\nformat ascii 1.0\nelement vertex 10\nproperty list uchar int\nend_header\n")


def test_rejects_unsupported_list_property_type() -> None:
    with pytest.raises(InvalidPLYError, match="Unsupported list property type"):
        _parse("ply\nformat ascii 1.0\nelement vertex 10\nproperty list bogus int idx\nend_header\n")


# ----------------------------------------------------------------------
# Unknown keyword.
# ----------------------------------------------------------------------


def test_rejects_unknown_keyword() -> None:
    with pytest.raises(InvalidPLYError, match="Unknown PLY header keyword"):
        _parse("ply\nformat ascii 1.0\nelement vertex 10\nbogus_keyword foo\nend_header\n")
