import io
import pytest

from topocore.io.ply.header_parser import PLYHeaderParser
from topocore.io.ply.exceptions import InvalidPLYError
from topocore.io.ply.enums import PLYFormat


def build_stream(text: str):
    return io.BytesIO(text.encode("utf-8"))


# ----------------------------
# BASIC HEADER PARSING
# ----------------------------

def test_parse_basic_ascii_header():
    header = """ply
format ascii 1.0
element vertex 1
property float x
property float y
property float z
end_header
"""

    stream = build_stream(header)

    result = PLYHeaderParser.parse(stream)

    assert result.format == PLYFormat.ASCII
    assert result.version == "1.0"
    assert len(result.elements) == 1
    assert result.elements[0].name == "vertex"
    assert result.elements[0].count == 1


def test_parse_multiple_elements():
    header = """ply
format ascii 1.0
element vertex 10
property float x
element face 5
property list uchar int vertex_indices
end_header
"""

    stream = build_stream(header)

    result = PLYHeaderParser.parse(stream)

    assert result.has_element("vertex")
    assert result.has_element("face")

    vertex = result.get_element("vertex")
    face = result.get_element("face")

    assert vertex.count == 10
    assert face.count == 5


# ----------------------------
# COMMENTS & OBJ INFO
# ----------------------------

def test_parse_comments_and_objinfo():
    header = """ply
format ascii 1.0
comment this is a comment
comment second comment
obj_info generated by TopoCore
element vertex 1
property float x
end_header
"""

    stream = build_stream(header)

    result = PLYHeaderParser.parse(stream)

    assert len(result.comments) == 2
    assert len(result.obj_info) == 1
    assert "this is a comment" in result.comments[0]


# ----------------------------
# LIST PROPERTY PARSING
# ----------------------------

def test_list_property_parsing():
    header = """ply
format ascii 1.0
element face 1
property list uchar int vertex_indices
end_header
"""

    stream = build_stream(header)

    result = PLYHeaderParser.parse(stream)

    face = result.get_element("face")
    assert face is not None

    prop = face.properties[0]

    assert hasattr(prop, "count_type")
    assert hasattr(prop, "value_type")


# ----------------------------
# INVALID CASES
# ----------------------------

def test_invalid_empty_header():
    header = """ply
end_header
"""

    stream = build_stream(header)

    with pytest.raises(InvalidPLYError):
        PLYHeaderParser.parse(stream)


def test_invalid_no_elements():
    header = """ply
format ascii 1.0
end_header
"""

    stream = build_stream(header)

    with pytest.raises(InvalidPLYError):
        PLYHeaderParser.parse(stream)


def test_invalid_missing_end_header():
    header = """ply
format ascii 1.0
element vertex 1
property float x
"""

    stream = build_stream(header)

    with pytest.raises(InvalidPLYError):
        PLYHeaderParser.parse(stream)


# ----------------------------
# FORMAT VARIANTS
# ----------------------------

def test_binary_format_parsing():
    header = """ply
format binary_little_endian 1.0
element vertex 1
property float x
end_header
"""

    stream = build_stream(header)

    result = PLYHeaderParser.parse(stream)

    assert result.format == PLYFormat.BINARY_LITTLE_ENDIAN


def test_big_endian_format_parsing():
    header = """ply
format binary_big_endian 1.0
element vertex 1
property float x
end_header
"""

    stream = build_stream(header)

    result = PLYHeaderParser.parse(stream)

    assert result.format == PLYFormat.BINARY_BIG_ENDIAN


# ----------------------------
# EDGE CASE: whitespace noise
# ----------------------------

def test_header_with_extra_whitespace():
    header = """ply

format ascii 1.0

element vertex 1
property float x

end_header
"""

    stream = build_stream(header)

    result = PLYHeaderParser.parse(stream)

    assert result.format == PLYFormat.ASCII
    assert result.vertex_count == 1