"""
topocore.io.crs.external
===========================

`ExternalCRSDetector`: looks for a `.prj` sidecar file next to a main
data file and resolves it to a real `CRS`. This is the shared
strategy for every format that carries no CRS of its own -- XYZ, CSV,
PTS, and PLY (confirmed during this project's own audit: none of
these formats has any internal CRS mechanism at all, unlike LAS/E57/
LandXML, each of which has its own dedicated, format-specific
detector instead).

Why `.prj` specifically, and only `.prj`
-------------------------------------------
`.prj` is not a TopoCore invention -- confirmed directly, it is the
real, decades-old sidecar convention from the ESRI Shapefile format
(`.shp`/`.shx`/`.dbf`/`.prj`, sharing one base filename), still the de
facto standard across the wider GIS ecosystem for exactly this
purpose: a plain-text file holding a single WKT string describing a
dataset's CRS, living next to the main data file. A `.json`-based
sidecar convention was deliberately NOT added alongside this --
confirmed there is no equivalent real-world precedent for a CRS
sidecar in that shape, so adding one now would mean inventing a
TopoCore-specific schema rather than detecting an established one.

**"ESRI-style" WKT1 is correctly accepted.** Confirmed directly:
`.prj` files conventionally hold the older, ESRI-flavored WKT1
dialect (e.g. `PROJCS["NAD_1983_UTM_Zone_10N", GEOGCS[...
DATUM["D_North_American_1983"...`), which differs syntactically from
modern WKT2 -- `CRS.from_wkt()` (backed by `pyproj`) parses this
dialect correctly with no special-casing needed here, verified with a
real ESRI-style WKT1 string generated by `pyproj` itself and
correctly resolved back to its own EPSG code.

**Sidecar files are read with `utf-8-sig`, not plain `utf-8`.**
Confirmed directly: `.prj` files produced by Windows/ESRI tooling
commonly carry a UTF-8 byte-order-mark (BOM). Reading with plain
`utf-8` leaves the decoded BOM character (`\ufeff`) at the very start
of the text, which then made `CRS.from_wkt()` fail on an otherwise
perfectly valid WKT string (it no longer began with `PROJCRS[`/
`GEOGCS[`/etc. literally) -- confirmed as a real defect during this
capability's own audit, fixed by reading with `utf-8-sig` instead,
which strips a leading BOM when present and behaves identically to
plain `utf-8` when it's absent.

Naming convention: same base filename, `.prj` extension --
`survey.xyz` -> `survey.prj`, replacing the original extension
entirely (`Path.with_suffix(".prj")`), matching the Shapefile
convention exactly (never `survey.xyz.prj`). Confirmed directly:
only this exact sidecar path is ever checked -- a file named
`survey.xyz.prj` sitting alongside a correctly-named `survey.prj` (or
existing on its own, with no `survey.prj` present) is never
consulted; there is no "try alternate candidate names" fallback.

Further findings from this module's own audit
---------------------------------------------------
- **A `.prj` file containing anything other than the CRS's own WKT
  verbatim -- leading blank lines, a comment, extra metadata -- is
  not parsed.** Confirmed directly: `CRS.from_wkt()` requires the
  entire string to be valid WKT; any leading text breaks its strict
  grammar and the result is `None`, not a best-effort extraction.
  This is a deliberate, conservative choice, not an oversight: real
  `.prj` files are conventionally a single line of pure WKT with no
  comment syntax of their own (confirmed against the real-world
  Shapefile/`.prj` convention during this module's own audit) --
  attempting to strip "likely comments" before parsing would mean
  guessing at an informal convention with no real precedent, risking
  silently mis-parsing a genuinely malformed sidecar as if it were
  valid.
- **A `.prj` file that exists but cannot be read (e.g. permission
  denied) is treated the same as one that doesn't exist -- `None`,
  not a raised exception.** `PermissionError` is a subclass of the
  `OSError` this module already catches. Confirmed this catch is
  structurally correct; confirmed separately that this project's own
  development environment runs as `root`, which bypasses Unix file
  permission checks entirely, so the actual OS-level denial itself
  could not be forced and demonstrated directly here.

Precedence policy: not applicable today, stated for future readers
--------------------------------------------------------------------
`apply_external_crs()` is used only by the 4 formats confirmed to
have zero internal CRS mechanism of their own (XYZ, CSV, PTS, PLY) --
there is no existing case where a `.prj` sidecar could compete with
an internally-detected CRS on the same file, so no precedence
decision has actually been exercised or tested here. Stated
explicitly for whoever adds a `.prj` fallback to a format with its
own native detector (LAS/LAZ, E57, LandXML) later: **an internally-
declared CRS always takes precedence over a `.prj` sidecar** -- a
`.prj` should only ever be consulted as a fallback when the format's
own native detector returns `None`, never used to override a CRS the
file already declares itself. This is a stated design intent for
future work, not behavior implemented or verified by this module.

Author
------
Hernán Mina

License
-------
MIT
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from topocore.geodesy import CRS
from topocore.geodesy.exceptions import CRSError
from topocore.pointcloud.pointcloud import PointCloud


@dataclass(frozen=True, slots=True)
class ExternalCRSDetector:
    """
    Stateless; the dataclass shape exists only to match the other
    detectors' own callable convention and to leave room for future
    configuration (e.g. an alternate sidecar extension) without
    changing the call shape. Construct with no arguments:
    `ExternalCRSDetector().detect(path)`.
    """

    def detect(self, path: str | Path) -> CRS | None:
        """
        Look for a `.prj` sidecar next to `path` and resolve it to a
        `CRS`.

        Returns
        -------
        `CRS` if a `.prj` file exists next to `path` and holds valid,
        parseable WKT (OGC or ESRI-style WKT1). `None` in every other
        case: no `.prj` file, an empty or whitespace-only `.prj` file,
        or one holding text that isn't valid WKT. Never raises for
        any of these -- exactly as with the format-specific
        detectors, an absent or unresolvable external CRS declaration
        is a normal, expected outcome, never an error, and never
        something that should block processing the main file.

        Raises
        ------
        FileNotFoundError
            If the main file at `path` does not exist. This is a
            genuine caller error; the sidecar's own absence is not
            checked in the same way, since a missing `.prj` is
            exactly the normal "no external CRS available" case.
        """
        resolved_path = Path(path)

        if not resolved_path.is_file():
            raise FileNotFoundError(f"File not found: '{resolved_path}'.")

        sidecar_path = resolved_path.with_suffix(".prj")

        if not sidecar_path.is_file():
            return None

        try:
            raw_text = sidecar_path.read_text(encoding="utf-8-sig")
        except (OSError, UnicodeDecodeError):
            return None

        if not raw_text.strip():
            return None

        try:
            return CRS.from_wkt(raw_text)
        except CRSError:
            return None


def apply_external_crs(cloud: PointCloud, path: str | Path) -> PointCloud:
    """
    Convenience wrapper for `PointCloudReader.read()` overrides:
    detects a `.prj` sidecar for `path` via `ExternalCRSDetector`
    and, if found, sets `cloud.crs` using the same
    `f"EPSG:{crs.epsg}"` (falling back to `crs.name` when there is no
    EPSG code) string convention already established by
    `topocore.geodesy.transform.transform_point_cloud()`, so a CRS
    string set via either path looks identical.

    **A confirmed, shared caveat with that existing convention** (not
    introduced here): a CRS with neither an EPSG code nor a real
    registered name (e.g. a custom PROJ4-defined CRS) has
    `pyproj`'s own generic placeholder, the literal string
    `"unknown"`, as its `.name`. Confirmed directly this is not new
    behavior -- `transform_point_cloud()` produces the exact same
    `"unknown"` string for the identical case. This is not fixed here
    in isolation to avoid the two mechanisms silently disagreeing;
    a caller working with genuinely unnamed CRS objects should be
    aware `cloud.crs == "unknown"` does not distinguish "a CRS
    literally named 'unknown'" from "no real name was available".

    Mutates and returns the same `cloud` object (via its own public
    `.crs` setter -- `PointCloudMetadata` is a plain mutable
    dataclass, confirmed directly; this never reaches into a private
    attribute). If no `.prj` is found or it doesn't resolve, `cloud`
    is returned completely unchanged -- this never raises for that
    reason, matching `ExternalCRSDetector.detect()`'s own contract.
    """
    detected = ExternalCRSDetector().detect(path)

    if detected is not None:
        cloud.crs = f"EPSG:{detected.epsg}" if detected.epsg is not None else detected.name

    return cloud


def apply_crs_with_native_priority(cloud: PointCloud, path: str | Path, native_crs: CRS | None) -> PointCloud:
    """
    For formats with their own native CRS detector (LAS/LAZ, E57):
    applies `native_crs` if present, otherwise falls back to
    `apply_external_crs()` (`.prj`). A valid native CRS is never
    overwritten by a `.prj` sidecar, even one declaring a genuinely
    different CRS -- confirmed directly this policy holds regardless
    of whether the `.prj` agrees or disagrees with the native value,
    since the `.prj` path is never even consulted once a native CRS
    is present.

    `native_crs` is the caller's own already-computed result from
    its own format-specific detector (e.g.
    `topocore.io.las.crs_detection.detect_crs()`) -- this function
    does not call any native detector itself, keeping it agnostic to
    which format is calling it.

    Same mutate-and-return contract as `apply_external_crs()`: the
    same `cloud` object is returned, via its own public `.crs`
    setter, never raising for an absent/unresolvable CRS from either
    source.
    """
    if native_crs is not None:
        cloud.crs = f"EPSG:{native_crs.epsg}" if native_crs.epsg is not None else native_crs.name
        return cloud

    return apply_external_crs(cloud, path)


__all__ = [
    "ExternalCRSDetector",
    "apply_crs_with_native_priority",
    "apply_external_crs",
]
